# Generated by Django 6.0.3 on 2026-03-08 20:36

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cid10',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('registro_ans', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('token_api', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_tuss', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('cnes', models.CharField(blank=True, max_length=20, null=True)),
                ('config_branding', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiais', to='gestao.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Medico', 'Médico'), ('Recepcao', 'Recepção'), ('Laboratorio', 'Laboratório')], default='Recepcao', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('google_calendar_token', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='gestao.clinica')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(db_index=True)),
                ('duracao_minutos', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('NaRecepcao', 'Na Recepção'), ('EmAtendimento', 'Em Atendimento'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Faltou', 'Faltou')], default='Agendado', max_length=50)),
                ('tipo', models.CharField(choices=[('Presencial', 'Presencial'), ('Telemedicina', 'Telemedicina')], default='Presencial', max_length=50)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, null=True)),
                ('checkin_status', models.CharField(default='Pendente', max_length=50)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Evolucao', 'Evolução'), ('Receita', 'Receita'), ('Atestado', 'Atestado')], max_length=50)),
                ('dados_estruturados', models.JSONField(blank=True, default=dict)),
                ('texto_rico_html', models.TextField(blank=True, null=True)),
                ('hash_integridade', models.CharField(blank=True, max_length=255, null=True)),
                ('versao', models.IntegerField(default=1)),
                ('assinado_digitalmente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestao.agendamento')),
                ('cid_10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.cid10')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('Imagem', 'Imagem'), ('Laudo', 'Laudo')], max_length=50)),
                ('url_arquivo', models.URLField()),
                ('upload_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='gestao.documentoclinico')),
            ],
        ),
        migrations.CreateModel(
            name='KitExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='ExameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exame', models.CharField(max_length=255)),
                ('codigo_tuss', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Realizado', 'Realizado'), ('Recebido', 'Recebido')], default='Pendente', max_length=50)),
                ('url_laudo_pdf', models.URLField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_lab', to='gestao.documentoclinico')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('VIEW', 'VIEW')], max_length=50)),
                ('tabela', models.CharField(max_length=100)),
                ('recurso_id', models.IntegerField()),
                ('dados_diff', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoteTiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100)),
                ('xml_gerado', models.TextField()),
                ('status_envio', models.CharField(default='Aberto', max_length=50)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.clinica')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_glosado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Parcial', 'Parcial'), ('Pago', 'Pago'), ('Glosa', 'Glosa'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50)),
                ('glosa_motivo', models.TextField(blank=True, null=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.agendamento')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.convenio')),
                ('lote_tiss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.lotetiss')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('nome_mae', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cns', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
                ('raca_cor', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('alertas_alergias', models.JSONField(blank=True, default=dict)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='gestao.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentimentoLgpd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(max_length=255)),
                ('aceito', models.BooleanField(default=False)),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.paciente'),
        ),
        migrations.CreateModel(
            name='PrescricaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=255)),
                ('posologia', models.TextField()),
                ('duracao', models.CharField(blank=True, max_length=100, null=True)),
                ('alerta_interacao', models.TextField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_receita', to='gestao.documentoclinico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemKitExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='gestao.kitexame')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='AgendamentoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_faturamento', to='gestao.agendamento')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.procedimento')),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('crm_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('rqe', models.CharField(blank=True, max_length=50, null=True)),
                ('conselho', models.CharField(choices=[('CRM', 'CRM'), ('CRO', 'CRO'), ('CRP', 'CRP')], default='CRM', max_length=20)),
                ('assinatura_digital_b64', models.TextField(blank=True, null=True)),
                ('pix_chave', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identidade_profissional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documentoclinico',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestao.profissional'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='responsavel_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicas_responsaveis', to='gestao.profissional'),
        ),
        migrations.CreateModel(
            name='ProfissionalClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_vinculo_inicio', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpo_clinico', to='gestao.clinica')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_clinica', to='gestao.profissional')),
            ],
            options={
                'unique_together': {('profissional', 'clinica')},
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('profissional_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.profissionalclinica')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('profissional_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.profissionalclinica')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.profissionalclinica'),
        ),
        migrations.CreateModel(
            name='RegraRepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_clinica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percentual_medico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigencia_inicio', models.DateField()),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.procedimento')),
                ('profissional_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.profissionalclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.clinica')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.sala'),
        ),
        migrations.CreateModel(
            name='SinaisVitais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pressao_arterial', models.CharField(blank=True, max_length=20, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frequencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('saturacao_o2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('glicemia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medido_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinais_vitais', to='gestao.documentoclinico')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('NaRecepcao', 'Na Recepção'), ('EmAtendimento', 'Em Atendimento'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Faltou', 'Faltou')], max_length=50)),
                ('status_novo', models.CharField(choices=[('Agendado', 'Agendado'), ('Confirmado', 'Confirmado'), ('NaRecepcao', 'Na Recepção'), ('EmAtendimento', 'Em Atendimento'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado'), ('Faltou', 'Faltou')], max_length=50)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='gestao.agendamento')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplatePep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estrutura', models.JSONField(default=dict)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='TermoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Sintoma', 'Sintoma'), ('Queixa', 'Queixa'), ('Outros', 'Outros')], max_length=50)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_clinica', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(max_length=50)),
                ('data_pagamento', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente'), ('Estornado', 'Estornado')], default='Pago', max_length=50)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('conta_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='gestao.contareceber')),
            ],
        ),
        migrations.CreateModel(
            name='CarteiraConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carteira', models.CharField(max_length=50, unique=True)),
                ('plano', models.CharField(blank=True, max_length=100, null=True)),
                ('validade_inicio', models.DateField(blank=True, null=True)),
                ('validade_fim', models.DateField(blank=True, null=True)),
                ('titular_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='gestao.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'convenio')},
            },
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabelas_preco', to='gestao.convenio')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.procedimento')),
            ],
            options={
                'unique_together': {('convenio', 'procedimento')},
            },
        ),
    ]
